use bookalab
    GO
GO
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Aaron', N'Mcdaniel');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Alec', N'Pacheco');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Amery', N'Maddox');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Aurelia', N'Edwards');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Aurelia', N'Melton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Beatrice', N'Gibson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Beverly', N'Anthony');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Bianca', N'Graham');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Bree', N'Perkins');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Brenden', N'Hebert');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Britanney', N'Dotson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Cadman', N'Chapman');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Camille', N'Conley');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Colorado', N'Blackwell');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Connor', N'Farrell');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Constance', N'Robinson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Cruz', N'Prince');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Darrel', N'Martin');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Darryl', N'Sweeney');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Dominic', N'Snyder');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Donovan', N'Snyder');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Dylan', N'Emerson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Elvis', N'Gay');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Emmanuel', N'Ortiz');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Emmanuel', N'Rodriguez');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Eugenia', N'Morton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ezra', N'Foley');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Fatima', N'Ford');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Felicia', N'Ellis');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Gail', N'Cantrell');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Georgia', N'Nolan');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Giacomo', N'Gallagher');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Glenna', N'Tyson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Grady', N'Guy');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Hamish', N'Browning');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Hanna', N'Mccullough');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Harper', N'Melton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Hedley', N'Weber');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Hermione', N'Camacho');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Hiroko', N'Franks');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ian', N'Douglas');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Igor', N'Lindsey');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Illana', N'Rocha');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ingrid', N'Reynolds');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ira', N'Freeman');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Irma', N'Santos');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Jaden', N'Beasley');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Jameson', N'Burke');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Jelani', N'Rosales');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Jena', N'Russo');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'John', N'Underwood');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Julie', N'Horton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Kaitlin', N'Lynch');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Keelie', N'Thompson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Kuame', N'Vega');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Lars', N'James');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Lucian', N'Donovan');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Lucian', N'Zamora');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Luke', N'Finch');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Maggie', N'Hess');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Maris', N'Summers');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Marshall', N'Briggs');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Mason', N'Delgado');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Melyssa', N'Cochran');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Mercedes', N'Jacobson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Mikayla', N'Drake');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Murphy', N'Tucker');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Odette', N'Benson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Odette', N'Sutton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Oleg', N'Adkins');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Orlando', N'Herman');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Pearl', N'Rodriquez');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Preston', N'Vasquez');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Quintessa', N'Robles');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Quon', N'Dominguez');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Rafael', N'Weaver');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Reagan', N'Carpenter');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Riley', N'Wilcox');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Rosalyn', N'Valdez');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ross', N'Decker');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ryan', N'Moran');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Sandra', N'Guerrero');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Scarlett', N'Sears');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Scott', N'Rios');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Shaeleigh', N'Navarro');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Sharon', N'Ware');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Shelly', N'Bradford');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Silas', N'Lowe');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Simone', N'Reynolds');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Stuart', N'Blankenship');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Tanisha', N'Davis');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Tasha', N'Hamilton');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Unity', N'Beard');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Ursa', N'Gilbert');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Walter', N'Witt');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Warren', N'Sampson');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Willa', N'Allen');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Winter', N'Gaines');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Xavier', N'Bowen');
INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Zelda', N'Huffman');


INSERT INTO bookalab.dbo.Person (name, last_name) VALUES (N'Denys', N'Sadilo');

INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2023-04-01 00:00:00.000', N'КС', N'3');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2022-05-27 00:00:00.000', N'КК', N'2');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2024-12-22 00:00:00.000', N'КС', N'3-2');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2024-10-21 00:00:00.000', N'КБ', N'3');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2023-11-25 00:00:00.000', N'КС', N'3-1');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2022-09-29 00:00:00.000', N'КІ', N'2');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2023-03-10 00:00:00.000', N'КС', N'2');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2022-08-19 00:00:00.000', N'КБ', N'2');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2024-12-27 00:00:00.000', N'КУ', N'3');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2025-02-08 00:00:00.000', N'ІК', N'1');
INSERT INTO bookalab.dbo.[Group] (start, prefix, sequence) VALUES (N'2023-04-01 00:00:00.000', N'ББ', N'1');


INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (3, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (5, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (6, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (7, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (8, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (9, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (10, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (12, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (13, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (14, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (16, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (17, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (20, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (21, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (23, 1);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (3, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (8, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (9, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (17, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (21, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (23, 3);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (6, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (7, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (10, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (13, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (14, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (16, 5);
INSERT INTO bookalab.dbo.StudentsInGroup (studentId, groupId) VALUES (20, 5);
